server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name justpaisa.in www.justpaisa.in testcodtech.shop www.testcodtech.shop 18.61.36.65 _;
    return 301 https://$host$request_uri;
}
