import { Lender, VendorVerificationRequest, SubscriptionPlan } from '../types';

export const mockLendersList: Lender[] = [
  {
    id: 'l1',
    institutionName: 'Nishanth Money Finance',
    institutionType: 'Financial Institution',
    logoUrl: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><rect width="100" height="100" rx="20" fill="%23003893"/><text x="50" y="62" font-family="Arial, sans-serif" font-size="32" font-weight="bold" fill="%23FFFFFF" text-anchor="middle">NMF</text></svg>',
    registrationNumber: 'FIN-IND-2021-1001',
    loanCategories: ['Business Loan', 'Working Capital'],
    minLoanAmount: 10000,
    maxLoanAmount: 100000,
    minInterestRate: 8.4,
    address: 'BKC Commercial Hub',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400051',
    distanceKm: 3.2,
    rating: 4.5,
    reviewCount: 128,
    contactPersonName: 'Nishanth Kumar (Proprietor)',
    contactUnlocked: true,
    phone: '+91 98200 11223',
    email: 'contact@nishanthmoneyfinance.com',
    whatsAppUrl: 'https://wa.me/919820011223',
  },
  {
    id: 'l2',
    institutionName: 'Rajesh Money Finance',
    institutionType: 'NBFC',
    logoUrl: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><rect width="100" height="100" rx="20" fill="%23059669"/><text x="50" y="62" font-family="Arial, sans-serif" font-size="32" font-weight="bold" fill="%23FFFFFF" text-anchor="middle">RMF</text></svg>',
    registrationNumber: 'FIN-IND-2019-1002',
    loanCategories: ['Business Loan', 'Term Loan'],
    minLoanAmount: 10000,
    maxLoanAmount: 150000,
    minInterestRate: 8.75,
    address: 'Lower Parel Finance Hub',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400013',
    distanceKm: 4.7,
    rating: 4.4,
    reviewCount: 96,
    contactPersonName: 'Rajesh Sharma (Managing Director)',
    contactUnlocked: true,
    phone: '+91 98333 44556',
    email: 'contact@rajeshmoneyfinance.com',
    whatsAppUrl: 'https://wa.me/919833344556',
  },
  {
    id: 'l3',
    institutionName: 'Suresh Money Finance',
    institutionType: 'Financial Institution',
    logoUrl: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><rect width="100" height="100" rx="20" fill="%237C3AED"/><text x="50" y="62" font-family="Arial, sans-serif" font-size="32" font-weight="bold" fill="%23FFFFFF" text-anchor="middle">SMF</text></svg>',
    registrationNumber: 'FIN-IND-2020-1003',
    loanCategories: ['Business Loan', 'Overdraft'],
    minLoanAmount: 15000,
    maxLoanAmount: 200000,
    minInterestRate: 8.9,
    address: 'Bandra Kurla Complex',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400051',
    distanceKm: 5.1,
    rating: 4.6,
    reviewCount: 112,
    contactPersonName: 'Suresh Gupta (Director)',
    contactUnlocked: true,
    phone: '+91 98111 22334',
    email: 'contact@sureshmoneyfinance.com',
    whatsAppUrl: 'https://wa.me/919811122334',
  },
  {
    id: 'l4',
    institutionName: 'Kishore Money Finance',
    institutionType: 'NBFC',
    logoUrl: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><rect width="100" height="100" rx="20" fill="%23D97706"/><text x="50" y="62" font-family="Arial, sans-serif" font-size="32" font-weight="bold" fill="%23FFFFFF" text-anchor="middle">KMF</text></svg>',
    registrationNumber: 'NBFC-RBI-MH-2015-8820',
    loanCategories: ['Business Loan', 'Equipment Loan'],
    minLoanAmount: 10000,
    maxLoanAmount: 100000,
    minInterestRate: 9.5,
    address: 'Viman Nagar Finance Park',
    city: 'Pune',
    state: 'Maharashtra',
    pincode: '411014',
    distanceKm: 6.3,
    rating: 4.3,
    reviewCount: 78,
    contactPersonName: 'Kishore Bajaj (Senior Credit Officer)',
    contactUnlocked: true,
    phone: '+91 98444 55667',
    email: 'contact@kishoremoneyfinance.com',
    whatsAppUrl: 'https://wa.me/919844455667',
  },
  {
    id: 'l5',
    institutionName: 'Venkatesh Money Finance',
    institutionType: 'Financial Institution',
    logoUrl: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><rect width="100" height="100" rx="20" fill="%232563EB"/><text x="50" y="62" font-family="Arial, sans-serif" font-size="32" font-weight="bold" fill="%23FFFFFF" text-anchor="middle">VMF</text></svg>',
    registrationNumber: 'FIN-IND-2022-1005',
    loanCategories: ['Business Loan', 'SME Loan'],
    minLoanAmount: 20000,
    maxLoanAmount: 150000,
    minInterestRate: 9.1,
    address: 'Kalina Commercial Complex',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400098',
    distanceKm: 7.8,
    rating: 4.4,
    reviewCount: 89,
    contactPersonName: 'Venkatesh Shah (Head of Loans)',
    contactUnlocked: true,
    phone: '+91 98555 66778',
    email: 'contact@venkateshmoneyfinance.com',
    whatsAppUrl: 'https://wa.me/919855566778',
  },
  {
    id: 'l6',
    institutionName: 'Ramesh Money Finance',
    institutionType: 'NBFC',
    logoUrl: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><rect width="100" height="100" rx="20" fill="%23DC2626"/><text x="50" y="62" font-family="Arial, sans-serif" font-size="32" font-weight="bold" fill="%23FFFFFF" text-anchor="middle">RMF</text></svg>',
    registrationNumber: 'NBFC-RBI-MH-2017-9102',
    loanCategories: ['Business Loan', 'Working Capital'],
    minLoanAmount: 10000,
    maxLoanAmount: 100000,
    minInterestRate: 9.8,
    address: 'Peninsula Business Park, Tower A',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400013',
    distanceKm: 8.6,
    rating: 4.2,
    reviewCount: 63,
    contactPersonName: 'Ramesh Verma (Regional Manager)',
    contactUnlocked: true,
    phone: '+91 98666 77889',
    email: 'contact@rameshmoneyfinance.com',
    whatsAppUrl: 'https://wa.me/919866677889',
  },
  {
    id: 'l7',
    institutionName: 'Mahesh Money Finance',
    institutionType: 'Financial Institution',
    logoUrl: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><rect width="100" height="100" rx="20" fill="%234F46E5"/><text x="50" y="62" font-family="Arial, sans-serif" font-size="32" font-weight="bold" fill="%23FFFFFF" text-anchor="middle">MMF</text></svg>',
    registrationNumber: 'FIN-IND-2018-1007',
    loanCategories: ['Business Loan', 'Term Loan'],
    minLoanAmount: 25000,
    maxLoanAmount: 200000,
    minInterestRate: 8.8,
    address: 'Bombay Dyeing Mills Compound',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400025',
    distanceKm: 9.2,
    rating: 4.3,
    reviewCount: 91,
    contactPersonName: 'Mahesh Mehta (VP Business Credit)',
    contactUnlocked: true,
    phone: '+91 98777 88990',
    email: 'contact@maheshmoneyfinance.com',
    whatsAppUrl: 'https://wa.me/919877788990',
  },
];

export const mockVerificationRequests: VendorVerificationRequest[] = [
  {
    id: 'vreq-1',
    vendorName: 'Ramesh Kumar',
    shopName: 'Kumar General Store',
    shopAddress: 'Shastri Nagar, Kanpur, Uttar Pradesh',
    city: 'Kanpur',
    state: 'Uttar Pradesh',
    requestedDate: '02 May 2024',
    requestedTime: '10:30 AM',
    status: 'Pending',
    mobileNumber: '+91 98765 43210',
    emailId: 'rameshkumar@gmail.com',
    dateOfBirth: '12 Jan 1988',
    panNumber: 'BGT PK1234A',
    aadhaarNumber: 'XXXX XXXX 1234',
    shopType: 'General Store',
    yearsInBusiness: '5 Years',
    shopImages: [
      'https://images.unsplash.com/photo-1604719312566-8912e9227c6a?q=80&w=400',
      'https://images.unsplash.com/photo-1578916171728-46686eac8d58?q=80&w=400',
      'https://images.unsplash.com/photo-1542838132-92c53300491e?q=80&w=400',
      'https://images.unsplash.com/photo-1583258292688-d0213dc5a3a8?q=80&w=400',
    ],
    shopLicensePdf: 'License_2024.pdf',
    gstCertificatePdf: 'GSTIN_09ABCDE1234F1Z5.pdf',
  },
  {
    id: 'vreq-2',
    vendorName: 'Suresh Yadav',
    shopName: 'Yadav Mobile Shop',
    shopAddress: 'Civil Lines, Kanpur, UP',
    city: 'Kanpur',
    state: 'Uttar Pradesh',
    requestedDate: '01 May 2024',
    requestedTime: '02:15 PM',
    status: 'Pending',
    mobileNumber: '+91 98123 45678',
    emailId: 'sureshyadav@gmail.com',
    dateOfBirth: '18 Aug 1992',
    panNumber: 'CYP PY8821B',
    aadhaarNumber: 'XXXX XXXX 5678',
    shopType: 'Electronics & Mobiles',
    yearsInBusiness: '3 Years',
    shopImages: [
      'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?q=80&w=400',
      'https://images.unsplash.com/photo-1556740738-b6a63e27c4df?q=80&w=400',
    ],
    shopLicensePdf: 'Shop_License_Yadav.pdf',
    gstCertificatePdf: 'GSTIN_09YADAV9988Z1.pdf',
  },
  {
    id: 'vreq-3',
    vendorName: 'Amit Verma',
    shopName: 'Verma Electricals',
    shopAddress: 'Mall Road, Kanpur, UP',
    city: 'Kanpur',
    state: 'Uttar Pradesh',
    requestedDate: '30 Apr 2024',
    requestedTime: '11:45 AM',
    status: 'Verified',
    mobileNumber: '+91 98999 11223',
    emailId: 'amitverma@gmail.com',
    dateOfBirth: '05 Nov 1985',
    panNumber: 'AVP PV9912C',
    aadhaarNumber: 'XXXX XXXX 9912',
    shopType: 'Electrical Hardware',
    yearsInBusiness: '7 Years',
    shopImages: [
      'https://images.unsplash.com/photo-1581092160607-ee22621dd758?q=80&w=400',
    ],
    shopLicensePdf: 'License_Verma.pdf',
    gstCertificatePdf: 'GSTIN_09VERMA7711X9.pdf',
  },
];

export async function fetchLenders(params?: {
  query?: string;
  city?: string;
  category?: string;
  radiusKm?: number;
}): Promise<{ lenders: Lender[]; hasActiveSubscription: boolean }> {
  const isSubscribed =
    typeof window !== 'undefined' &&
    (localStorage.getItem('sbni_vendor_subscribed') === 'true' ||
     localStorage.getItem('sbni_subscribed') === 'true');

  const mappedLenders = mockLendersList.map((l) => ({
    ...l,
    contactUnlocked: isSubscribed,
  }));

  return { lenders: mappedLenders, hasActiveSubscription: isSubscribed };
}

export async function fetchSubscriptionPlans(role: 'VENDOR' | 'LENDER' = 'VENDOR'): Promise<SubscriptionPlan[]> {
  if (role === 'LENDER') {
    return [
      {
        id: 'l-plan-1',
        code: 'WEEKLY',
        name: 'Weekly Trial Plan',
        description: 'Verify vendors & review applications for 7 days',
        price: 499,
        originalPrice: 799,
        durationDays: 7,
        durationLabel: '7 Days',
        roleTarget: 'LENDER',
        features: [
          'Verify Up to 10 Vendors',
          'Full Vendor Profile & KYC Access',
          'GST & License Document Verification',
          'Direct Contact & Call Vendor',
        ],
      },
      {
        id: 'l-plan-2',
        code: 'MONTHLY',
        name: 'Monthly Professional Plan',
        description: 'Popular choice for active lenders & credit managers',
        price: 1499,
        originalPrice: 2499,
        durationDays: 30,
        durationLabel: '30 Days',
        isPopular: true,
        roleTarget: 'LENDER',
        features: [
          'Unlimited Vendor Verifications',
          'Full KYC & GST Verification Reports',
          'Direct Phone, Email & WhatsApp Access',
          'Priority Verified Lender Badge',
          'Dedicated Account Support',
        ],
      },
      {
        id: 'l-plan-3',
        code: 'QUARTERLY',
        name: 'Quarterly Growth Plan',
        description: '3 Months access for expanding loan portfolios',
        price: 3899,
        originalPrice: 5999,
        durationDays: 90,
        durationLabel: '90 Days',
        roleTarget: 'LENDER',
        features: [
          'Everything in Monthly Plan',
          'Bulk Vendor Import & Lead Exports',
          'Custom Risk Score Assessment',
          'Dedicated Regional Support Manager',
        ],
      },
      {
        id: 'l-plan-4',
        code: 'HALF_YEARLY',
        name: 'Half-Yearly Enterprise Plan',
        description: '6 Months complete lending platform suite',
        price: 6999,
        originalPrice: 10999,
        durationDays: 180,
        durationLabel: '180 Days',
        roleTarget: 'LENDER',
        features: [
          '6 Months Unlimited Access',
          'API Integration for Loan Originating',
          'Premium Lender Listing in Top Spot',
          'Priority Customer Escalation Support',
        ],
      },
      {
        id: 'l-plan-5',
        code: 'YEARLY',
        name: 'Yearly Institutional Plan',
        description: '1 Year full access with maximum savings',
        price: 11999,
        originalPrice: 19999,
        durationDays: 365,
        durationLabel: '365 Days',
        isBestValue: true,
        roleTarget: 'LENDER',
        features: [
          '365 Days Full Unlimited Platform Usage',
          'Dedicated Enterprise Account Manager',
          'Custom API & CRM Sync',
          'Zero Commission / 100% Direct Leads',
        ],
      },
    ];
  }

  // Default Vendor Plans
  return [
    {
      id: 'v-plan-1',
      code: 'WEEKLY',
      name: 'Weekly Trial Plan',
      description: 'Quick access to nearby lenders for 7 days',
      price: 199,
      originalPrice: 399,
      durationDays: 7,
      durationLabel: '7 Days',
      roleTarget: 'VENDOR',
      features: [
        'Unlock Nearby Lender Phone Numbers',
        'Direct WhatsApp Chat Access',
        'Search Lenders within 10 KM Radius',
        'Instant Application Submission',
      ],
    },
    {
      id: 'v-plan-2',
      code: 'MONTHLY',
      name: 'Monthly Growth Plan',
      description: 'Most popular plan for business owners seeking capital',
      price: 599,
      originalPrice: 999,
      durationDays: 30,
      durationLabel: '30 Days',
      isPopular: true,
      roleTarget: 'VENDOR',
      features: [
        'Unlimited Lender Phone & WhatsApp Unlocks',
        'Direct Email & Branch Contact Details',
        'Pan-India Lender Discovery',
        'Verified Vendor Trust Badge',
        'Dedicated Customer Support',
      ],
    },
    {
      id: 'v-plan-3',
      code: 'QUARTERLY',
      name: 'Quarterly Business Plan',
      description: '3 Months uninterrupted lender discovery',
      price: 1399,
      originalPrice: 2499,
      durationDays: 90,
      durationLabel: '90 Days',
      roleTarget: 'VENDOR',
      features: [
        'Everything in Monthly Plan',
        'Priority Loan Request Routing',
        'Digital KYC Document Storage',
        'Multi-Bank Comparison Tool',
      ],
    },
    {
      id: 'v-plan-4',
      code: 'HALF_YEARLY',
      name: 'Half-Yearly Scale Plan',
      description: '6 Months active funding suite for growing SMEs',
      price: 2499,
      originalPrice: 4499,
      durationDays: 180,
      durationLabel: '180 Days',
      roleTarget: 'VENDOR',
      features: [
        '6 Months Unlimited Platform Access',
        'Guaranteed Fast-Track KYC Approval',
        'Direct Dedicated Relationship Support',
        'New Lender Notifications',
      ],
    },
    {
      id: 'v-plan-5',
      code: 'YEARLY',
      name: 'Yearly VIP Enterprise Plan',
      description: '1 Year complete access with maximum savings',
      price: 4499,
      originalPrice: 7999,
      durationDays: 365,
      durationLabel: '365 Days',
      isBestValue: true,
      roleTarget: 'VENDOR',
      features: [
        '365 Days Unlimited Contact Access',
        'Zero Middleman Fees Guarantee',
        'VIP Priority Verification Status',
        '24/7 Dedicated Account Manager',
      ],
    },
  ];
}
